# Docker
# Build and push an image to Docker Hub

trigger:
- master

resources:
- repo: self

variables:
  # Docker Hub service connection (create it in Azure DevOps)
  dockerRegistryServiceConnection: 'DockerHub'

  # Docker Hub repo (use your Docker Hub username)
  imageRepository: 'adil22/app1nginx'

  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and Push to Docker Hub
  jobs:  
  - job: Build
    displayName: Build and Push
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push image to Docker Hub
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          latest
          $(tag)
